CREATE TABLE IF NOT EXISTS unified_movies (id VARCHAR(32) PRIMARY KEY, title VARCHAR(255) NOT NULL, original_title VARCHAR(255), metadata JSON NOT NULL, data_version VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS external_movie_mappings (movie_id VARCHAR(32) NOT NULL, source VARCHAR(16) NOT NULL, external_id VARCHAR(64) NOT NULL, method VARCHAR(64), confidence DECIMAL(5,4), needs_review BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(source, external_id));
CREATE TABLE IF NOT EXISTS movie_features (movie_id VARCHAR(32) NOT NULL, model_version VARCHAR(64) NOT NULL, features JSON NOT NULL, PRIMARY KEY(movie_id, model_version));
CREATE TABLE IF NOT EXISTS movie_watch_providers (movie_id VARCHAR(32) NOT NULL, region CHAR(2) NOT NULL, provider_id INT NOT NULL, provider_name VARCHAR(128) NOT NULL, provider_type VARCHAR(16) NOT NULL, tmdb_link TEXT, checked_at TIMESTAMP NOT NULL, PRIMARY KEY(movie_id, region, provider_id, provider_type));
CREATE TABLE IF NOT EXISTS collection_runs (id BIGINT AUTO_INCREMENT PRIMARY KEY, source VARCHAR(16) NOT NULL, mode VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, success_count INT NOT NULL DEFAULT 0, failure_count INT NOT NULL DEFAULT 0, started_at TIMESTAMP NOT NULL, finished_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS model_versions (id VARCHAR(64) PRIMARY KEY, data_version VARCHAR(64) NOT NULL, metrics JSON NOT NULL, artifact_path TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS recommendation_rounds (id VARCHAR(64) PRIMARY KEY, room_id VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP NOT NULL, closed_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS recommendation_results (id BIGINT AUTO_INCREMENT PRIMARY KEY, round_id VARCHAR(64) NOT NULL, movie_id VARCHAR(32) NOT NULL, rank_no INT NOT NULL, group_score DECIMAL(7,6) NOT NULL, model_version VARCHAR(64) NOT NULL, data_version VARCHAR(64) NOT NULL, explanation JSON NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS recommendation_member_scores (result_id BIGINT NOT NULL, user_id VARCHAR(64) NOT NULL, score DECIMAL(7,6) NOT NULL, evidence JSON NOT NULL, PRIMARY KEY(result_id, user_id));
CREATE TABLE IF NOT EXISTS recommendation_exclusions (round_id VARCHAR(64) NOT NULL, movie_id VARCHAR(32) NOT NULL, reasons JSON NOT NULL, PRIMARY KEY(round_id, movie_id));
CREATE TABLE IF NOT EXISTS recommendation_events (id BIGINT AUTO_INCREMENT PRIMARY KEY, round_id VARCHAR(64) NOT NULL, user_id VARCHAR(64), movie_id VARCHAR(32), event_type VARCHAR(32) NOT NULL, payload JSON, created_at TIMESTAMP NOT NULL);

