export interface Provider {
  provider_id: number;
  name: string;
  type: string;
}

export interface Movie {
  internal_id: string;
  tmdb_id: number;
  kobis_code?: string;
  title: string;
  title_ko?: string;
  title_en?: string;
  original_title?: string;
  overview: string;
  genres: string[];
  keywords: string[];
  cast: string[];
  directors: string[];
  countries: string[];
  language: string;
  release_date?: string;
  runtime?: number;
  certification?: string;
  vote_average: number;
  vote_count: number;
  popularity: number;
  poster_path?: string;
  providers: Provider[];
  provider_link?: string;
  recommendations?: number[];
  similar?: number[];
  recommendation_eligible: boolean;
}

export const MOVIES: Movie[] = [
  {
    internal_id: "mov_1",
    tmdb_id: 581387,
    title: "은하의 약속",
    overview: "인류의 새로운 터전을 찾기 위해 은하계 외곽으로 떠난 우주 탐사선. 지구에 홀로 남아 기다리는 딸과의 약속을 지키기 위해 시공간의 한계를 넘어 펼쳐지는 감동적인 우주 모험 드라마.",
    genres: ["SF", "드라마", "모험"],
    keywords: ["우주", "가족", "모험", "시공간", "감동"],
    cast: ["김별", "이우주"],
    directors: ["이하늘"],
    countries: ["KR"],
    language: "ko",
    release_date: "2024-06-01",
    runtime: 118,
    vote_average: 8.1,
    vote_count: 2400,
    popularity: 75,
    poster_path: "https://media.themoviedb.org/t/p/w500/sotIdprxcrA2ZRKfH0UZOK9wBuA.jpg",
    providers: [
      { provider_id: 8, name: "Netflix", type: "flatrate" },
      { provider_id: 356, name: "TVING", type: "flatrate" }
    ],
    provider_link: "https://www.themoviedb.org/movie/581387/watch",
    recommendations: [2, 5],
    similar: [2, 5],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_2",
    tmdb_id: 488188,
    title: "여름의 식탁",
    overview: "바쁘고 고단한 일상에 지친 세 친구가 동해안 작은 어촌 마을의 여름 집으로 모여든다. 제철 식재료로 매일 근사한 요리를 나누며 서로의 상처를 치유하고 청춘의 의미를 되찾아가는 힐링 푸드 드라마.",
    genres: ["코미디", "드라마", "음식"],
    keywords: ["우정", "요리", "여름", "힐링", "청춘"],
    cast: ["박바다", "이햇살"],
    directors: ["최여름"],
    countries: ["KR"],
    language: "ko",
    release_date: "2023-08-12",
    runtime: 104,
    vote_average: 7.8,
    vote_count: 900,
    popularity: 52,
    poster_path: "https://media.themoviedb.org/t/p/w500/gFvbihAO1aH5j7JTH8RdKqQiO31.jpg",
    providers: [{ provider_id: 97, name: "Watcha", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/488188/watch",
    recommendations: [1],
    similar: [1, 3],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_3",
    tmdb_id: 508642,
    title: "검은 복도",
    overview: "오래전 일련의 의문사 사건 이후 폐쇄되었던 옛 시골 고등학교. 자율학습 피날레를 위해 남겨진 학생들과 교사들이 한밤중 닫힌 복도에서 마주치는 초자연적 공포와 숨겨진 잔혹한 진실.",
    genres: ["공포", "스릴러", "미스터리"],
    keywords: ["귀신", "학교", "스릴러", "미스터리"],
    cast: ["정밤", "한어둠"],
    directors: ["김지옥"],
    countries: ["KR"],
    language: "ko",
    release_date: "2022-10-31",
    runtime: 112,
    certification: "청소년관람불가",
    vote_average: 6.9,
    vote_count: 4100,
    popularity: 81,
    poster_path: "https://media.themoviedb.org/t/p/w500/6X7J26RghbLpGjyYP768dsUpKli.jpg",
    providers: [
      { provider_id: 701, name: "Coupang Play", type: "flatrate" },
      { provider_id: 356, name: "TVING", type: "flatrate" },
      { provider_id: 97, name: "Watcha", type: "flatrate" }
    ],
    similar: [2],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_4",
    tmdb_id: 567604,
    title: "도시의 탐정",
    overview: "비상한 기억력과 엉뚱한 수사법을 자랑하는 사설 탐정이 화려한 서울 한복판에서 벌어지는 대규모 금융 범죄 사건에 휘말린다. 끊임없는 사건사고와 통쾌한 맨몸 액션이 펼쳐지는 액션 코미디.",
    genres: ["액션", "코미디", "범죄"],
    keywords: ["탐정", "서울", "추리", "액션", "통쾌"],
    cast: ["김별", "윤빛"],
    directors: ["박추리"],
    countries: ["KR"],
    language: "ko",
    release_date: "2025-02-14",
    runtime: 112,
    vote_average: 8.3,
    vote_count: 6100,
    popularity: 92,
    poster_path: "https://media.themoviedb.org/t/p/w500/w6Jk8BHohhoKBUcxGeSyDQGWGWc.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/567604/watch",
    recommendations: [2],
    similar: [2],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_5",
    tmdb_id: 157336,
    title: "인터스텔라",
    overview: "세계 각국의 정부와 경제가 완전히 붕괴된 미래. 시들어가는 지구를 뒤로하고 인류의 생존을 위해 우주에 새로 발견된 워몰을 통해 시공간을 넘어 탐사를 떠나는 전직 NASA 파일럿 쿠퍼의 장대한 이야기.",
    genres: ["SF", "드라마", "모험"],
    keywords: ["우주", "가족", "블랙홀", "워몰", "시공간", "감동"],
    cast: ["매튜 매커너히", "앤 해서웨이", "제시카 차스테인"],
    directors: ["크리스토퍼 놀란"],
    countries: ["US"],
    language: "en",
    release_date: "2014-11-06",
    runtime: 169,
    vote_average: 8.6,
    vote_count: 32000,
    popularity: 120,
    poster_path: "https://media.themoviedb.org/t/p/w500/auQjFBfCWSL6DpQhWVCZ6wFtDm6.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }, { provider_id: 97, name: "Watcha", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/157336/watch",
    recommendations: [1, 12],
    similar: [1, 12],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_6",
    tmdb_id: 635302,
    title: "귀멸의 칼날",
    overview: "혈귀로 변한 동생 네즈코를 인간으로 되돌리기 위해 귀살대에 들어간 탄지로. 짧은 기간 동안 40명 이상의 사람이 행방불명된 무한열차에 탑승해 귀살대 최강의 검사 렌고쿠 쿄쥬로와 함께 강력한 혈귀에 맞선다.",
    genres: ["애니메이션", "액션", "판타지", "드라마"],
    keywords: ["혈귀", "칼", "동생", "귀살대", "무한열차", "소년만화"],
    cast: ["하나에 나츠키", "키토 아카리"],
    directors: ["소토자키 하루오"],
    countries: ["JP"],
    language: "ja",
    release_date: "2020-10-16",
    runtime: 117,
    vote_average: 8.4,
    vote_count: 15000,
    popularity: 95,
    poster_path: "https://media.themoviedb.org/t/p/w500/8OGrD5t6swQFmoZ1pGL2YJa277P.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/635302/watch",
    recommendations: [11],
    similar: [11],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_7",
    tmdb_id: 24428,
    title: "어벤져스",
    overview: "지구의 안보가 위협받는 위기의 상황, 쉴드(S.H.I.E.L.D.)의 수장 닉 퓨리는 세계를 구하기 위해 아이언맨, 캡틴 아메리카, 토르, 헐크, 블랙 위도우, 호크아이 등 슈퍼히어로들을 모아 '어벤져스' 팀을 결성한다.",
    genres: ["액션", "SF", "모험"],
    keywords: ["마블", "Marvel", "MCU", "슈퍼히어로", "우주", "히어로"],
    cast: ["로버트 다우니 주니어", "크리스 에반스", "마크 러팔로"],
    directors: ["조스 웨던"],
    countries: ["US"],
    language: "en",
    release_date: "2012-04-26",
    runtime: 143,
    vote_average: 8.2,
    vote_count: 28000,
    popularity: 110,
    poster_path: "https://media.themoviedb.org/t/p/w500/l1SWn7SdwvAowNfC4ojV2B9LDgs.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/24428/watch",
    recommendations: [8, 13, 14],
    similar: [8, 13, 14],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_8",
    tmdb_id: 315635,
    title: "스파이더맨",
    overview: "'시빌 워' 이후 토니 스타크에게 발탁되어 세상을 구할 히어로가 되길 꿈꾸는 피터 파커. 평범한 고등학생 일상 속에서 마을을 위협하는 강력한 적 벌처에 맞서 진짜 히어로로 거듭나기 위한 좌충우돌 라이프.",
    genres: ["액션", "모험", "SF", "코미디"],
    keywords: ["마블", "Marvel", "MCU", "스파이더맨", "영웅", "성장", "고등학생"],
    cast: ["톰 홀랜드", "마이클 키튼", "로버트 다우니 주니어"],
    directors: ["존 와츠"],
    countries: ["US"],
    language: "en",
    release_date: "2017-07-05",
    runtime: 133,
    vote_average: 8.0,
    vote_count: 22000,
    popularity: 105,
    poster_path: "https://media.themoviedb.org/t/p/w500/x4uMWPwYUljcc6LWJSZNq19HryO.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/315635/watch",
    recommendations: [7, 14],
    similar: [7, 14],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_9",
    tmdb_id: 109445,
    title: "겨울왕국",
    overview: "서로가 최고였던 자매 엘사와 안나. 하지만 동생을 해칠까 봐 자신의 통제할 수 없는 얼음 마법을 숨긴 엘사는 왕국을 영원한 겨울로 물들인 채 떠나고, 안나는 신비로운 왕국의 겨울을 해제하고 언니를 찾기 위해 거친 모험을 시작한다.",
    genres: ["애니메이션", "가족", "판타지", "음악", "모험"],
    keywords: ["디즈니", "Disney", "엘사", "안나", "얼음", "마법", "자매"],
    cast: ["크리스텐 벨", "이디나 멘젤", "조시 개드"],
    directors: ["크리스 버크", "제니퍼 리"],
    countries: ["US"],
    language: "en",
    release_date: "2013-11-27",
    runtime: 102,
    vote_average: 8.5,
    vote_count: 21000,
    popularity: 115,
    poster_path: "https://media.themoviedb.org/t/p/w500/5UfIxiiEbqfT1X1SEyV4EZFcTZU.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/109445/watch",
    recommendations: [10, 16, 17],
    similar: [10, 16, 17],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_10",
    tmdb_id: 150540,
    title: "인사이드 아웃",
    overview: "모든 사람의 머릿속에 존재하는 감정 컨트롤 본부. 기쁨, 슬픔, 버럭, 까칠, 소심 다섯 감정들이 11살 라일리에게 행복을 선사하기 위해 분투하는 가운데, 우연한 사고로 기쁨이와 슬픔이가 본부를 이탈하면서 라일리의 마음에 거대한 위기가 찾아온다.",
    genres: ["애니메이션", "가족", "코미디", "드라마", "판타지"],
    keywords: ["픽사", "Pixar", "디즈니", "Disney", "감정", "성장", "기쁨", "슬픔"],
    cast: ["에이미 포일러", "필리스 스미스"],
    directors: ["피트 닥터"],
    countries: ["US"],
    language: "en",
    release_date: "2015-06-19",
    runtime: 95,
    vote_average: 8.7,
    vote_count: 19500,
    popularity: 110,
    poster_path: "https://media.themoviedb.org/t/p/w500/xKJyZ5rbOlaDIjvudGVKQ6kko2W.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/150540/watch",
    recommendations: [9, 15, 16],
    similar: [9, 15, 16],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_11",
    tmdb_id: 129,
    title: "센과 치히로의 행방불명",
    overview: "이사 가던 날, 우연히 의문의 터널을 지나 인간이 들어가선 안 될 신들의 세계로 들어간 10살 소녀 치히로. 돼지로 변해버린 부모님을 구하고 현실 세계로 돌아가기 위해 온천장 온유야에서 마녀 유바바 밑에서 일하며 펼치는 환상적인 모험.",
    genres: ["애니메이션", "판타지", "모험", "가족"],
    keywords: ["지브리", "Ghibli", "미야자키 하야오", "하쿠", "마법", "온천"],
    cast: ["히라기 루미", "이리노 미유"],
    directors: ["미야자키 하야오"],
    countries: ["JP"],
    language: "ja",
    release_date: "2001-07-20",
    runtime: 125,
    vote_average: 8.8,
    vote_count: 23000,
    popularity: 130,
    poster_path: "https://media.themoviedb.org/t/p/w500/8TEs6twIANAc2qiU8m17JO8Ujcx.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/129/watch",
    recommendations: [6, 19],
    similar: [6, 19],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_12",
    tmdb_id: 155,
    title: "다크 나이트",
    overview: "배트맨과 짐 고든 경위, 신임 검사 하비 덴트가 힘을 합쳐 고담시의 범죄 조직들을 일탕 소탕하던 중, 광기와 범죄를 예술로 삼는 정체불명의 악당 조커가 등장해 고담시 전체를 거대한 혼란과 시험에 빠뜨린다.",
    genres: ["액션", "범죄", "스릴러", "드라마"],
    keywords: ["DC", "배트맨", "조커", "영웅", "고담시", "크리스토퍼 놀란"],
    cast: ["크리스찬 베일", "히스 레저", "아론 에크하트"],
    directors: ["크리스토퍼 놀란"],
    countries: ["US"],
    language: "en",
    release_date: "2008-07-18",
    runtime: 152,
    vote_average: 8.9,
    vote_count: 31000,
    popularity: 140,
    poster_path: "https://media.themoviedb.org/t/p/w500/nftQJb9550PtYFXhmTs7XiN0QhR.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/155/watch",
    recommendations: [5, 7],
    similar: [5, 7],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_13",
    tmdb_id: 447365,
    title: "가디언즈 오브 갤럭시 Volume 3",
    overview: "가모라를 잃고 슬픔에 빠져 있던 피터 퀼이 위기에 처한 동료 로켓을 구하기 위해 다시 가디언즈 팀을 이끌고 은하계를 넘나드는 위험천만한 임무에 나선다. 로켓의 과거 비화와 가디언즈 멤버들의 뜨거운 우정 이야기.",
    genres: ["액션", "SF", "모험", "코미디"],
    keywords: ["마블", "Marvel", "MCU", "우주", "영웅", "가디언즈", "로켓"],
    cast: ["크리스 프랫", "조이 살다나", "데이브 바티스타"],
    directors: ["제임스 건"],
    countries: ["US"],
    language: "en",
    release_date: "2023-05-03",
    runtime: 150,
    vote_average: 8.4,
    vote_count: 12000,
    popularity: 135,
    poster_path: "https://media.themoviedb.org/t/p/w500/waTQqjV1dvGlbCAhN2VAIierdev.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/447365/watch",
    recommendations: [7, 8, 14, 18],
    similar: [7, 8, 14, 18],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_14",
    tmdb_id: 634649,
    title: "스파이더맨: 노 웨이 홈",
    overview: "미스테리오에 의해 정체가 세상에 밝혀진 피터 파커가 세상을 되돌리기 위해 닥터 스트레인지의 도움을 받던 중 마법 주문의 균열로 인해 차원의 문이 열리고, 다른 멀티버스 차원의 강력한 숙적들이 모여들며 펼쳐지는 스파이더맨 최대의 위기.",
    genres: ["액션", "SF", "모험", "판타지"],
    keywords: ["마블", "Marvel", "MCU", "스파이더맨", "영웅", "멀티버스", "닥터 스트레인지"],
    cast: ["톰 홀랜드", "젠데이아", "베네딕트 컴버배치"],
    directors: ["존 와츠"],
    countries: ["US"],
    language: "en",
    release_date: "2021-12-15",
    runtime: 148,
    vote_average: 8.5,
    vote_count: 22000,
    popularity: 145,
    poster_path: "https://media.themoviedb.org/t/p/w500/j2vwjzuofol93OcSn8xAHJiTEoz.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/634649/watch",
    recommendations: [7, 8, 13],
    similar: [7, 8, 13],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_15",
    tmdb_id: 1022789,
    title: "인사이드 아웃 2",
    overview: "13살이 된 라일리의 머릿속 감정 컨트롤 본부에 '불안', '당황', '따분', '부러움'이라는 새로운 감정들이 불쑥 등장한다. 기존 감정들과 새 감정들의 주도권 싸움 속에서 진정한 자아를 찾아가는 틴에이저 라일리의 성장통.",
    genres: ["애니메이션", "가족", "코미디", "드라마"],
    keywords: ["디즈니", "Disney", "픽사", "Pixar", "감정", "성장", "불안"],
    cast: ["에이미 포일러", "마야 호크"],
    directors: ["켈시 맨"],
    countries: ["US"],
    language: "en",
    release_date: "2024-06-12",
    runtime: 96,
    vote_average: 8.6,
    vote_count: 8500,
    popularity: 160,
    poster_path: "https://media.themoviedb.org/t/p/w500/Z0aXIB7qTsO4oicCVyJxTZFYrg.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/1022789/watch",
    recommendations: [10, 16],
    similar: [10, 16],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_16",
    tmdb_id: 976573,
    title: "엘리멘탈",
    overview: "불, 물, 공기, 흙 4원소가 함께 살아가는 엘리멘트 시티. 재치 있고 불처럼 뜨거운 성격의 '엠버'가 감성적이고 물처럼 흐르는 '웨이드'를 만나 서로 다른 특성을 이해하며 스파크 터지는 우정과 사랑을 만들어가는 감동 판타지.",
    genres: ["애니메이션", "가족", "코미디", "판타지", "로맨스"],
    keywords: ["디즈니", "Disney", "픽사", "Pixar", "원소", "사랑", "가족", "엠버", "웨이드"],
    cast: ["레아 루이스", "마무두 아티"],
    directors: ["피터 손"],
    countries: ["US"],
    language: "en",
    release_date: "2023-06-14",
    runtime: 102,
    vote_average: 8.5,
    vote_count: 11000,
    popularity: 150,
    poster_path: "https://media.themoviedb.org/t/p/w500/ldwoWIp7jfCuyNfEXnocsIRtACR.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/976573/watch",
    recommendations: [9, 10, 15],
    similar: [9, 10, 15],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_17",
    tmdb_id: 502356,
    title: "위시",
    overview: "마법의 왕국 로샤스에서 모두의 소원을 이뤄준다는 마그니피코 왕의 비밀을 알게 된 총명한 소녀 아샤. 모두의 꿈과 소원을 되찾기 위해 유성 '별'과 함께 용기를 내어 세상에서 가장 특별한 기적을 만들어낸다.",
    genres: ["애니메이션", "가족", "판타지", "음악", "모험"],
    keywords: ["디즈니", "Disney", "마법", "소원", "음악", "아샤"],
    cast: ["아리아나 드보스", "크리스 파인"],
    directors: ["크리스 버크", "폰 비라순손"],
    countries: ["US"],
    language: "en",
    release_date: "2023-11-22",
    runtime: 95,
    vote_average: 7.5,
    vote_count: 4500,
    popularity: 90,
    poster_path: "https://media.themoviedb.org/t/p/w500/9oRTYGGqRuMGmC6MzII5Q0ofOuz.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/502356/watch",
    recommendations: [9, 16],
    similar: [9, 16],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_18",
    tmdb_id: 293660,
    title: "데드풀과 울버린",
    overview: "자신의 소중한 사람들과 세상을 구하기 위해 히어로 인생 최대의 위기를 맞이한 데드풀이 상극이자 은둔 중인 울버린을 찾아가 협력하며 펼쳐지는 거침없고 통쾌한 R등급 마블 멀티버스 액션 스펙터클.",
    genres: ["액션", "코미디", "SF"],
    keywords: ["마블", "Marvel", "MCU", "데드풀", "울버린", "영웅", "멀티버스"],
    cast: ["라이언 레이놀즈", "휴 잭맨"],
    directors: ["숀 레비"],
    countries: ["US"],
    language: "en",
    release_date: "2024-07-24",
    runtime: 127,
    vote_average: 8.3,
    vote_count: 9500,
    popularity: 180,
    poster_path: "https://media.themoviedb.org/t/p/w500/zhqrRtBVHAbHqLl9O5dMYAHeyFH.jpg",
    providers: [{ provider_id: 337, name: "Disney Plus", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/293660/watch",
    recommendations: [7, 13, 14],
    similar: [7, 13, 14],
    recommendation_eligible: true
  },
  {
    internal_id: "mov_19",
    tmdb_id: 653346,
    title: "그대들은 어떻게 살 것인가",
    overview: "전쟁 중 어머니를 잃은 11살 소년 마히토가 시골 저택으로 이사한 후, 정체불명의 사기조류 푸른 왜가리를 만나 이세계로 발을 들여놓는다. 생과 사가 교차하는 시공간을 초월한 신비로운 환상 여정.",
    genres: ["애니메이션", "판타지", "모험", "드라마"],
    keywords: ["지브리", "Ghibli", "미야자키 하야오", "환상", "이세계"],
    cast: ["산토키 소마", "스다 마사키"],
    directors: ["미야자키 하야오"],
    countries: ["JP"],
    language: "ja",
    release_date: "2023-10-25",
    runtime: 124,
    vote_average: 8.2,
    vote_count: 6000,
    popularity: 100,
    poster_path: "https://media.themoviedb.org/t/p/w500/ijXdXakqXBfKrm0kyHpVnTFEYz0.jpg",
    providers: [{ provider_id: 8, name: "Netflix", type: "flatrate" }],
    provider_link: "https://www.themoviedb.org/movie/653346/watch",
    recommendations: [11],
    similar: [11],
    recommendation_eligible: true
  }
];
